[package]
name = "self-banking"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.1.5", features = ["server"] }

sea-orm = { version = "1.1.11", features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
    "macros",
] }
sea-orm-migration = "1.1.11"

dotenv = "0.15.0"